"""empty message

Revision ID: 7502a186c724
Revises: fbbf7a5512c5
Create Date: 2024-02-15 00:05:23.450473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7502a186c724'
down_revision = 'fbbf7a5512c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.drop_constraint('note_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('note_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
